"""change column name

Revision ID: 539848bb298d
Revises: 7c7f45ff6385
Create Date: 2025-02-06 10:10:42.668887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539848bb298d'
down_revision: Union[str, None] = '7c7f45ff6385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ### 